name: Build Mod

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Make out dir
        run: mkdir out/
      - name: Copy assets file
        run: cp -r assets/ out/
      - name: Copy data file
        run: cp -r data/ out/
      - uses: actions/checkout@v2
      - name: Copy pack.mcmeta
        run: cp pack.mcmeta out/pack.mcmeta
      - name: Copy LICENSE
        run: cp LICENSE out/LICENSE
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AnvilCraft-${{ github.run_id }}-1.18
          path: out/
